# Generated by Django 4.2.20 on 2025-04-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_poll_end_time_poll_max_voters_poll_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='max_voters',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='poll',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='poll',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
