# Generated by Django 4.2.20 on 2025-04-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_remove_poll_end_time_remove_poll_max_voters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='description',
        ),
        migrations.AddField(
            model_name='polloption',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
